frequency: 30
silent_tf_failure: false
two_d_mode: true
publish_tf: true
permit_corrected_publication: false
print_diagnostics: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

imu0: /imu/data
imu0_config: [false, false, false, # x, y, z
              false, false, true, # r, p, y
              false, false, false, # vx, vy, vz
              false, false, true, # vr, vp, vy
              true, true, false] # ax, ay, az
imu0_remove_gravitational_acceleration: true

# TODO: process_noise_covariance
# TODO: initial_estimate_covariance